---
version: 3

build_arg_defaults:
  ANSIBLE_GALAXY_CLI_COLLECTION_OPTS: -vv

dependencies:
  galaxy:
      collections:
      - ansible.controller
      - infra.aap_configuration
      - infra.ee_utilities
      - ansible.posix
      - ansible.platform
      - containers.podman
      - awx.awx
  python:
  - awxkit
  - python-dateutil
  - pyyaml
  system:
  - libxml2-devel
  - gcc
  - systemd-devel
  - python3.11-devel

additional_build_files:
  - src: ansible.cfg
    dest: configs
additional_build_steps:
  prepend_galaxy:
    - ADD _build/configs/ansible.cfg /etc/ansible/ansible.cfg
images:
  base_image:
    name: registry.redhat.io/ansible-automation-platform-25/ee-supported-rhel8:latest
    
