---
- name: Backup
  hosts: all
  gather_facts: true
  become: true
  force_handlers: true

  tasks:
  # Edit this playbook with the modules needed for your hypervisor and any other steps required for taking a backup
    - name: Create a snapshot of your existing server
      community.vmware.vmware_guest_snapshot:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        datacenter: "{{ datacenter_name }}"
        folder: "/{{ datacenter_name }}/vm/"
        name: "{{ guest_name }}"
        state: present
        snapshot_name: rhel_ipu_snapshot
        description: snapshot_before_rhel_in_place_upgrade
      delegate_to: localhost

...
