---
- name: Analysis
  hosts: all
  gather_facts: true
  become: true
  force_handlers: true

  tasks:
    - name: Generate preupgrade analysis report
      ansible.builtin.import_role:
        name: infra.leapp.analysis

    - name: Enable reviewing the analysis through cockpit
      when: use_cockpit
      block:
      - name: Install cockpit and cockpit LEAPP
        ansible.builtin.package:
          name: cockpit, cockpit-leapp
          state: present

      - name: Open the cockpit firewall port
        ansible.posix.firewalld:
          service: cockpit
          state: enabled
          permanent: true
          immediate: true
          offline: true
        
      - name: Start the cockpit service
        ansible.builtin.service:
          name: cockpit
          state: started

...
