---
- name: Remediate
  hosts: all
  become: true
  force_handlers: true
  vars_files:
    ../vars/remediation_list.yml
  tasks:
    - name: Perform remediations on the system
      ansible.builtin.import_role:
        name: infra.leapp.remediate
    # Add additional remediation tasks for upgrading RHEL 7 systems
    # or other fixes that are not covered by the remediate playbooks here

...
